# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1alntUyRXYr6G04RbuZ7WGQvOITzLt4la
"""

import numpy as np
import pandas as pd

df=pd.read_csv('sales_data.csv')
df

#Handle missing values
df.replace("", pd.NA, inplace=True)
missing_values = df.isnull().sum()
df

# Remove duplicate rows
df = df.drop_duplicates()
df

#  Standardize text values
df["Gender"] = df["Gender"].str.lower()
df["Country"] = df["Country"].replace({
    "U.S.A": "United States",
    "USA": "United States"
})
df

#Convert date format as dd-mm-yyy
df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True, errors='coerce')
df["Order Date"] = df["Order Date"].dt.strftime('%d-%m-%Y')
df

#Rename column headers
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df

#  Check and fix data types
df["quantity"] = df["quantity"].astype("int")
df["price"] = df["price"].astype("float")
df["total"] = df["total"].astype("float")
df

print("Missing values per column:\n", missing_values)
print("\nCleaned DataFrame:\n", df)